# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Moving Forward
email: elliottking93@gmail.com
description: >- 
  React, Python, NodeJS, Rails. Writing technical blogs is much easier than writing about
  my personality, but I will do my best. Hopefully I won't run out of space. When I was
  ten, I defeated Bill Ga

permalink: /:year/:month/:title/

# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://elliott-king.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: send_bitcoin
github_username: elliott-king
linkedin_username: elliottwking

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
